// Données de démonstration locales — en attendant le branchement Supabase.
// Voir design_handoff_le_fil/README.md pour le modèle de données réel.
import type { Lot, Project, Task } from '../types/models';
import { shiftDays, toDay } from '../lib/dates';

function iso(offsetDays: number | null): string | null {
  if (offsetDays === null) return null;
  return toDay(shiftDays(new Date(), offsetDays));
}

const now = new Date().toISOString();

export const SEED_PROJECTS: Project[] = [
  { id: 'proj_maison', userId: 'local', name: 'Maison', color: '#e8402a', position: 0 },
  { id: 'proj_site', userId: 'local', name: 'Site perso', color: '#2a8a97', position: 1 },
  { id: 'proj_lecture', userId: 'local', name: 'Lectures', color: '#7a4fa3', position: 2 },
];

export const SEED_LOTS: Lot[] = [
  {
    id: 'lot_1',
    userId: 'local',
    projectId: 'proj_maison',
    title: 'Réviser la chaudière',
    body: 'Appeler le chauffagiste avant l’hiver.',
    startDate: null,
    due: iso(-2),
    repeat: 'none',
    startTime: null,
    endTime: null,
    location: '',
    done: false,
    position: null,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'lot_2',
    userId: 'local',
    projectId: 'proj_site',
    title: 'Refondre la page d’accueil',
    body: '',
    startDate: iso(-5),
    due: iso(0),
    repeat: 'none',
    startTime: null,
    endTime: null,
    location: '',
    done: false,
    position: null,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'lot_3',
    userId: 'local',
    projectId: 'proj_site',
    title: 'Écrire l’article sur le design system',
    body: '',
    startDate: null,
    due: iso(4),
    repeat: 'none',
    startTime: null,
    endTime: null,
    location: '',
    done: false,
    position: null,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'lot_4',
    userId: 'local',
    projectId: 'proj_lecture',
    title: 'Finir « Les villes invisibles »',
    body: '',
    startDate: null,
    due: iso(18),
    repeat: 'none',
    startTime: null,
    endTime: null,
    location: '',
    done: false,
    position: null,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'lot_5',
    userId: 'local',
    projectId: null,
    title: 'Trier les photos de vacances',
    body: '',
    startDate: null,
    due: null,
    repeat: 'none',
    startTime: null,
    endTime: null,
    location: '',
    done: false,
    position: null,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'lot_6',
    userId: 'local',
    projectId: 'proj_maison',
    title: 'Changer le joint du robinet',
    body: '',
    startDate: null,
    due: iso(-10),
    repeat: 'none',
    startTime: null,
    endTime: null,
    location: '',
    done: true,
    position: null,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'lot_7',
    userId: 'local',
    projectId: null,
    title: 'Anniversaire de Julie',
    body: 'Cadeau + gâteau.',
    startDate: null,
    due: iso(3),
    repeat: 'yearly',
    startTime: null,
    endTime: null,
    location: '',
    done: false,
    position: null,
    createdAt: now,
    updatedAt: now,
  },
];

const noTimeLocation = { startTime: null, endTime: null, location: '' } as const;

export const SEED_TASKS: Task[] = [
  {
    id: 'task_1',
    lotId: 'lot_1',
    label: 'Trouver un numéro',
    startDate: null,
    due: null,
    ...noTimeLocation,
    done: true,
    position: 0,
  },
  {
    id: 'task_2',
    lotId: 'lot_1',
    label: 'Prendre rendez-vous',
    startDate: null,
    due: iso(-1),
    ...noTimeLocation,
    done: false,
    position: 1,
  },
  {
    id: 'task_3',
    lotId: 'lot_2',
    label: 'Maquette mobile',
    startDate: null,
    due: iso(0),
    ...noTimeLocation,
    done: false,
    position: 0,
  },
  {
    id: 'task_4',
    lotId: 'lot_2',
    label: 'Choisir la typo',
    startDate: null,
    due: iso(9),
    ...noTimeLocation,
    done: false,
    position: 1,
  },
];
